"""2nd Migration

Revision ID: fc40e1f00f03
Revises: 967bdf9f3aad
Create Date: 2019-02-11 23:31:57.058350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc40e1f00f03'
down_revision = '967bdf9f3aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('upVotes', sa.Integer(), nullable=True))
    op.drop_column('pitches', 'upvotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('upvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'upVotes')
    # ### end Alembic commands ###
